### PR TITLE
fix(album-color-theme): improve theming consistency across UI elements

### LINKED ISSUE #2232: [Suggestion]: Improve `Album Color Theme` Patch
### 1. Properly theme Search Bar-
    
image

### 2. Properly Theme Pop-Ups-
    
image

### 3. Properly Theme Seekbar-

image

### 4. Properly Theme Share Menu-
       
image

### 5. Proper fluid transitions between each Album Color Theme change rather then suddenly changing the colours drastically in a flash when next song starts, I was thinking of a ripple animation from the centre or something similar to make it visually appealing.

### PR DESCRIPTION
**Pull request by Sunkist18**
- Add theming for search bar background
- Add theming for popup/dialog backgrounds (toast, paper-dialog)
- Add theming for seekbar with gradient colors (toggleable via config)
- Refactor types (Config, Renderer) for better type safety
- Fix getMixedColor binding issue in updateColor method
- Add i18n support for enable-seekbar option (en, ko)

 ## Summary

  This PR improves the `Album Color Theme` plugin by extending theming support to previously unthemed UI elements.

  ### Changes

  | Area | Description |
  |------|-------------|
  | Search Bar | Applies album color to search bar background |
  | Pop-ups | Themes toast notifications and dialog backgrounds |
  | Seekbar | Adds gradient color theming with toggle option |
  | Code Quality | Refactors types (`Config`, `Renderer`) for better type safety |
  | i18n | Adds English and Korean translations for new option |

  ### Screenshots

  | Before | After |
  |--------|-------|
  | 348555232-5cd80e6d-df2c-4712-b040-2a6a2820371a| image |
  | image | image |
  | image | image |
| image | image |

  ### New Option

  A new toggle has been added to enable/disable seekbar theming:

image

  ---

Closes #2232

### CODE REVIEW

File: src/plugins/album-color-theme/index.ts [hunk 1]
```diff
@@ -207,24 +212,50 @@ export default createPlugin<
...
+        '--paper-progress-active-color-2',
+        getMixedColor('#ff2791', COLOR_KEY, alpha, 1.75),
+        'important',
+      );
+
+      document.documentElement.style.setProperty(
+        '--yt-spec-inverted-background',
+        getMixedColor('#f3f3f3', COLOR_KEY, alpha, 1.75),
         'important',
       );
```
Comment (Su-Yong) [inline src/plugins/album-color-theme/index.ts]: How about extracting the repeated part as a new function?

Comment (Sunkist18) [reply src/plugins/album-color-theme/index.ts]: Done! I've extracted the repeated pattern as suggested.

Quick question: I found a bug where the plugin doesn't properly disable. 
Should I fix it here or in a separate PR/issue?

Comment (Su-Yong) [reply src/plugins/album-color-theme/index.ts]: I recommend to fix it in a new PR

File: src/plugins/album-color-theme/index.ts [hunk 2]
```diff
@@ -207,25 +212,75 @@ export default createPlugin<
...
+        key: string,
+        alpha: number,
+        ratioMultiply?: number,
+      ) => {
+        element.style.setProperty(
+          property,
+          getMixedColor(color, key, alpha, ratioMultiply),
+          'important',
+        );
+      };
```
Comment (Su-Yong) [inline src/plugins/album-color-theme/index.ts]: this isn't efficient. I mean reuse a upper code.

Comment (Sunkist18) [reply src/plugins/album-color-theme/index.ts]: I fixed it.

**Comment by Su-Yong** [comment]
LGTM. I'll be merge it
