### PR TITLE
synced-lyrics: make the lyrics search more reliable

### LINKED ISSUE #2332: [Bug]: (Synced Lyrics) In some unknown conditions, lyrics doesn't display even if lyrics exists and found on LRCLIB.
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 40, kernel: 6.9.12-200.fc40.x86_64

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

_No response_

### Reproduction steps

1. Play song
2. Open lyrics tab
2.1 Lyrics not displayed
3. Open DevTools > Network and find "search?*" request

### Expected Behavior

Lyrics displayed

### Actual Behavior

"No lyrics found for this song"
*See in additional information attached files*

### Enabled plugins

1. Downloader
2. In-app menu
3. Precise volume
4. Shortcuts (and MPRIS)
5. Discord Rich Presence
6. Music Together
7. Synced Lyrics

### Additional Information

Снимок экрана от 2024-08-04 16-18-35

Снимок экрана от 2024-08-04 16-12-33

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
Related #473
Closes #2332

Compares each artist individually, by splitting on `&` and `,` , generating all the possible permutations.

e.g. for `Sam Tinnesz & Silverberg` and `Silverberg & Sam Tinnesz`
it will compare

- `Sam Tinnesz` with `Silverberg`: 57.20% similarity
- `Sam Tinnesz` with `Sam Tinnesz`: 100% similarity
- `Silverberg` with `Silverberg`: 100% similarity
- `Silverberg` with `Sam Tinnesz`: 57.20% similarity

it will then pick the maximum ratio, if the similarity is lower than 90% it will ignore the lyric result

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Note that this does not ensure that both artists are present, it only ensures that one of the participating artists is there

**Comment by ArjixWasTaken** [comment]
Also fixed a general bug, were the song info was undefined if a song was already playing before our code kicked in

**Comment by ArjixWasTaken** [comment]
Looks like youtube music is not consistent on how it displays multiple artists, so I also split on commas.

**Comment by ArjixWasTaken** [comment]
After all these small changes, it is now way more reliable.

File: src/plugins/synced-lyrics/renderer/lyrics/fetch.ts [hunk 1]
```diff
@@ -73,8 +73,9 @@ export const getLyricsList = async (
     track_name: songData.title,
   });
 
-  if (songData.album) {
-    query.set('album_name', songData.album);
+  const album = `${songData.album}`.trim();
```
Comment (JellyBrick) [inline src/plugins/synced-lyrics/renderer/lyrics/fetch.ts]: This change is not needed.

File: src/providers/song-info-front.ts [hunk 2]
```diff
@@ -200,6 +200,11 @@ export default (api: YoutubePlayer) => {
     for (const status of ['playing', 'pause'] as const) {
       video.addEventListener(status, playPausedHandlers[status]);
     }
+
+    const data = api.getVideoData();
```
Comment (JellyBrick) [inline src/providers/song-info-front.ts]: Do not use this method. This method comes with a number of issues.

e.g. can't fetch some data. See #1332

P.S. If using youtubei.js to resolve this issue, the user's IP may be flagged due to duplicate requests.

File: src/plugins/synced-lyrics/renderer/lyrics/fetch.ts (hunk 1 above)
Comment (ArjixWasTaken) [reply src/plugins/synced-lyrics/renderer/lyrics/fetch.ts]: It is needed due to `.getVideoData()` not having the album info on startup.

It won't be needed when that other piece of code is fixed.

File: src/providers/song-info-front.ts (hunk 2 above)
Comment (ArjixWasTaken) [reply src/providers/song-info-front.ts]: It would only make a duplicate request on startup (if we used youtubei.js to fetch the data).

Can't imagine it being flagged.

Comment (ArjixWasTaken) [reply src/providers/song-info-front.ts]: Made it a bit more reliable, it now attempts to grab the album name.
It will fail to do so if an ad is playing at that exact moment, but the album name will simply be undefined in that scenario.

Comment (ArjixWasTaken) [reply src/providers/song-info-front.ts]: eureka!

**Comment by ArjixWasTaken** [comment]
I won't remove the `undefined` check for the album name, I keep randomly getting that issue.
Please don't ask me to remove it, it won't harm anyone and it is actually doing smth.

**Comment by ArjixWasTaken** [comment]
Anyway, can this PR get merged, so I can start working on multi-provider support?

**Comment by ArjixWasTaken** [comment]
I've been daily driving this and I haven't encountered any bug.

**Review by JellyBrick — APPROVED** [review]

**Comment by Dzheremi2** [comment]
> I've been daily driving this and I haven't encountered any bug.

I have compiled the latest commit and the bug is still presented. Song `Wolves` from #2332 is still cannot fetch lyrics and results in DevTools are the same.

**Comment by ArjixWasTaken** [comment]
it appears I made a mistake in the regex

**Comment by ArjixWasTaken** [comment]
Thanks for the report @Dzheremi2 .

In my daily testing I didn't encounter any songs that have multiple artists 😓
