### PR TITLE
fix playPause bugs by directly playPause video element

### LINKED ISSUE #129: Media Keys Broken with Auto-Unpause
When the plugin auto-confirm-when-paused is enabled, after a while the pause media key won't work anymore (when you push it nothing happens). I suspect this is because the app immediately unpauses thinking it's been paused by youtube. Pushing the buttons on the app still seem to work though

### LINKED ISSUE #145: Play/Pause menu item in taskbar icon Context Menu doesn't pause
The play/pause button in the taskbar icon's menu won't pause the current playing song. It will play the song if the track is currently paused but pausing it doesn't work.

### PR DESCRIPTION
**Pull request by Araxeus**
this PR makes song-controls.playPause() affect directly the video element in the page. (instead of just pressing space)
This fixes several bugs when pausing the video when it isn't focused
(from tray/taskbar/notifications)

fix #145 , fix #129

also sneaky change because of previous comments:
song-info-front is directly required instead of checking if file exist (since we already know it exist)

### CODE REVIEW

File: providers/song-info-front.js [hunk 1]
```diff
@@ -10,17 +10,16 @@ ipcRenderer.on("update-song-info", async (_, extractedSongInfo) => {
...
 		realXHR.addEventListener(
 			"readystatechange",
 			() => {
-				if (realXHR.readyState == 4 && realXHR.status == 200) {
-					if (realXHR.responseURL.includes("/player")) {
+				if (realXHR.readyState === 4 && realXHR.status === 200
+					&& realXHR.responseURL.includes("/player")) {
 						// if the request contains the song info, send the response to ipcMain
 						ipcRenderer.send("song-info-request", realXHR.responseText);
-					}
```
Comment (Araxeus) [inline providers/song-info-front.js:23]: this is a pretty random lint but xo was warning me about those so i decided why not

File: providers/song-controls-front.js [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+module.exports = () => {
+    ipcRenderer.on("playPause", () => {
+        if (!videoStream) {
+            videoStream = document.querySelector(".video-stream");
+        }
+
+        if (videoStream.paused) {
+            videoStream.play();
+        } else {
+            videoStream.yns_pause();
```
Comment (th-ch) [inline providers/song-controls-front.js]: `Uncaught TypeError: videoStream.yns_pause is not a function` shouldn't it be
```suggestion
            videoStream.pause();
```
?

**Review by th-ch — COMMENTED** [review]
The `auto-confirm-when-paused` unpauses the video each time because it is paused programmatically (instead of emulating the space key), is it expected?

File: providers/song-controls-front.js (hunk 2 above)
Comment (Araxeus) [reply providers/song-controls-front.js]: ~~Thats weird... where did you get that error?
`pause()` doesn't work on the youtube video stream.
`yns_pause()` is a function that I extracted from the actual youtube video stream and it works in all my tests~~

~~I didn't test it with `auto-confirm-when-paused`, we'll have to see what to do about that~~

~~maybe use this new ipc("playPause") only if `auto-confirm-when-paused` isn't enabled 
and else use spacebar as before. but then it wont fix this issue for users that have that plugin enabled :(~~

Comment (th-ch) [reply providers/song-controls-front.js]: Maybe it depends on the platform 🤔  -> A workaround can be to check if `yns_pause` is an existing function, in which case it can be called, otherwise call `pause`.
Agreed about using it only if `auto-confirm-when-paused` isn't enabled, it's not perfect but this way it won't break stuff!

Comment (Araxeus) [reply providers/song-controls-front.js]: I just realized 2 things:
1. `auto-confirm-when-paused` was enabled for me all along while testing
2.  `pause()` works only when YoutubeNonStop isn't active (because YoutubeNonStop overrides the original function)
 `yns_pause()` is the original `pause()` function that YoutubeNonStop saved and registered

   

source: [YoutubeNonStop.overrideVideoPause()](https://github.com/lawfx/YoutubeNonStop/blob/7b6b97b31bb3fd2078179660db0fd3fcc7062259/autoconfirm.js#L115-L133)


With the latest changes, it should all work flawlessly for you right?

Comment (Araxeus) [reply providers/song-controls-front.js:13]: I Tested this with `auto-confirm-when-paused` and it seems to work flawlessly for me.

Is it maybe possible you didn't update your locally deployed version of `YoutubeNonStop`?
If not - I'm really confused as to how it can be that it works for me but not for you... platform difference again??

**Review by th-ch — APPROVED** [review]
Looks ok after some local testing ✅ 
Thanks for the improvement, merging!
