### PR TITLE
fix: discord rich presence connection status

### LINKED ISSUE #2620: [Bug]: Discord Rich Presence displays "Connected" while Discord is closed
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.6.1

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Last Known Working YouTube Music (Application) version

_No response_

### Reproduction steps

1. Open Discord
2. Open YTM
3. Enable "Discord Rich Presence" YTM plugin
4. Confirm Discord Rich Presence status says "Connected"
5. Close Discord using right click + quit
6. Observe Discord Rich Presence status

### Expected Behavior

Discord Rich Presence status should be along the lines of "Disconnected" as there's nothing to be connected to.

### Actual Behavior

Discord Rich Presence status says "Connected" despite Discord being closed

### Enabled plugins

1. Discord Rich Presence
2. Album color theme
3. AdBlock

### Additional Information

I've also noticed that YouTube Music only hooks to Discord on YTM startup, which isn't ideal, as Discord has updates every now and then.

### PR DESCRIPTION
**Pull request by daika7ana**
Fixed the false "Connected" status in the `discord-rich-presence` plugin. 

The `isConnected()` function now includes an extra check to ensure the Discord RPC is actually connected, not just instantiated.
This makes the connection status properly reflect the RPC client's state. 

Fixes #2620.

### CODE REVIEW

File: src/plugins/discord/main.ts [hunk 1]
```diff
@@ -110,7 +110,8 @@ export const clear = () => {
 };
 
 export const registerRefresh = (cb: () => void) => refreshCallbacks.push(cb);
-export const isConnected = () => info.rpc !== null;
+export const isConnected = () =>
+  info.rpc !== null && info.rpc?.isConnected === true;
```
Comment (JellyBrick) [inline src/plugins/discord/main.ts]:
```suggestion
  info.rpc?.isConnected;
```

**Review by JellyBrick — CHANGES_REQUESTED** [review]

File: src/plugins/discord/main.ts (hunk 1 above)
Comment (daika7ana) [reply src/plugins/discord/main.ts]: Fixed in a separate commit to keep it clean as a one-liner. Guess I was a bit tired when I made the fix and missed the obvious.

**Review by JellyBrick — APPROVED** [review]
